### ISSUE TITLE
Error partitioning device

### ISSUE THREAD

**Issue by aymanmahran** [nh2/chrubuntu#1]
When I run:

`SCRIPT=$(NIX_PATH=nixpkgs=https://github.com/nh2/nixpkgs/archive/95aa1b3c8b.tar.gz nix-build --no-link '<nixpkgs/nixos>' -A config.system.build.chromebook-removable-media-partitioning-script -I nixos-config=nixos-rootfs.nix) && $SCRIPT "$DEVICE"`

I get this error:
`warning: Nix search path entry 'nixos-rootfs.nix' does not exist, ignoring
error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at /nix/store/36ip5p2rrqbjw7gh8plpagzmhjp6i758-95aa1b3c8b.tar.gz/nixos/default.nix:1:60
(use '--show-trace' to show detailed location information)`

I'm running nix build tools on Ubuntu 19.10

**Comment by nh2** [comment]
Are you running it from the checked-out repository?

> `Nix search path entry 'nixos-rootfs.nix' does not exist, ignoring`

suggests that it cannot find the file `nixos-rootfs.nix` which is at the top-level of the repo.

**Comment by aymanmahran** [comment]
I'm sorry it's my problem. Looks like the file was corrupt for some reason. I re-downloaded the repository again and it worked! Thanks

**Comment by nh2** [comment]
Great that it worked out!
