### ISSUE TITLE
Suspend doesn't work properly

### ISSUE THREAD

**Issue by aymanmahran** [nh2/chrubuntu#2]
I managed to install Ubuntu 18.04 successfully on my Samsung XE500C21 chromebook. However, when suspending the laptop and then waking it up, I found that the laptop state is not saved, and it boots back to the OS verification screen as if it was shut down. I tried enabling suspend to disk (hibernation) and it worked, but I was wondering if there is a way to fix the suspend to RAM issue as hibernation is a much slower.

**Comment by aymanmahran** [comment]
It turns out to be a kernel-related issues. On kernels above 5.0.0, the laptop reboots after resuming. I downgraded kernel from 5.3.1 to 4.15.0 and suspend now works.

**Comment by nh2** [comment]
I think you should report that bug ustream in the kernel bugzilla.

I also had a boot bug with my Chromebook and it got fixed eventually: https://bugzilla.kernel.org/show_bug.cgi?id=203463
